name: update
on: push

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Add secrets and run eas update
        env:
          EXPO_PUBLIC_acr: ${{ secrets.EXPO_PUBLIC_acr }}
          EXPO_PUBLIC_acrsecret: ${{ secrets.EXPO_PUBLIC_acrsecret }}
          EXPO_PUBLIC_genius: ${{ secrets.EXPO_PUBLIC_genius }}
          EXPO_PUBLIC_gpt: ${{ secrets.EXPO_PUBLIC_gpt }}
          EXPO_PUBLIC_musixmatch: ${{ secrets.EXPO_PUBLIC_musixmatch }}
          EXPO_PUBLIC_spotify: ${{ secrets.EXPO_PUBLIC_spotify }}
          EXPO_PUBLIC_youtube: ${{ secrets.EXPO_PUBLIC_youtube }}
        run: eas update --auto
